#!/usr/bin/env bash

SCRIPT="$(realpath "${BASH_SOURCE[0]}")"
GITDIR="$(cd "$(dirname "$SCRIPT")" && pwd)/.."

PASSENTRY=tokens/master
ARCHIVE="$GITDIR/files/archive.tar.gz.gpg"

BLACKLIST=('random_seed' '.#*' '*.lock' 'S.*' '*.sw*' '.*.sw*' '*~' '.*~'
  '*.db' '*.db-shm' '*.db-wal' 'lock' 'lockMCMD')

promptpass() {
  local password

  echo -n 'PASSPHRASE: ' >&2
  read -rs password
  echo >&2

  echo "$password"
}

passphrase() {
  [[ -n "$PASSPHRASE" ]] && { echo "$PASSPHRASE";  return 0; }
  pass show "$PASSENTRY" || promptpass
}

enc() {
  > "$ARCHIVE" gpg \
    --batch --symmetric --pinentry-mode=loopback --passphrase-file=<(passphrase)
}

dec() {
  < "$ARCHIVE" gpg \
    --decrypt --batch --pinentry-mode=loopback --passphrase-file=<(passphrase)
}

commit() {
  git rev-parse HEAD
}

archive() {
  tar czf - --exclude-from=<(printf "%s\n" "${BLACKLIST[@]}") \
    --ignore-failed-read -C "$GITDIR/files" "private"
}

unarchive() {
  local dst="${1:-$GITDIR/files}"

  [[ -e "$ARCHIVE" ]] || { echo "$ARCHIVE not found"; exit 1; }

  [[ -d "$dst" ]] || mkdir -p "$dst"

  tar xzf - --preserve-permissions --no-same-owner --overwrite \
    -C "$dst"
}

lock() {
  archive | enc
}

unlock() {
  dec | unarchive "$1"
}

peekarchive() {
  dec | tar zt
}

diffarchive() {
  # extract the archive to tmp dir and diff recursively with private dir
  local tmpdir="$GITDIR/files/tmp.$1"

  [[ -d "$GITDIR/files/private" ]] || return 1

  [[ -e "$ARCHIVE" ]] && unlock "$tmpdir" || return 1

  command diff --recursive --exclude-from=<(printf "%s\n" "${BLACKLIST[@]}") \
    "$GITDIR/files/private" "$tmpdir/private"
}

pre-commit() {
  diffarchive "$(commit)" && exit 0
  lock && git add .
}

post-merge() {
  diffarchive "$(commit)" || unlock
}

post-checkout() {
  local newhead="$2"
  local branchflag="$3"

  # flag == 0 -> file checkout
  [[ "$branchflag" == 1 ]] || exit 1

  local tmpdir="$GITDIR/files/tmp.$newhead"
  unlock "$tmpdir" || exit 1
}

main() {
  cd "$GITDIR" || exit 1

  git config --local core.hooksPath "$GITDIR/.githooks"

  NAME="$(basename "$0")"

  if [[ "$NAME" == hookscript ]]; then
    declare -F "$1" && "$@"
    exit $?
  fi

  declare -F "$NAME" && "$NAME" "$@"
}

main "$@"
