#!/usr/bin/env bash

blacklist=(
    "--exclude=supervise"
    "--exclude=system-connections"
    "--exclude=credentials.txt"
    "--exclude=*~"
    "--exclude=*.new-*"
)

private=(
    /etc/security/sudo_authorized_keys
    /etc/NetworkManager/system-connections
    /etc/openvpn/privateinternetaccess/credentials.txt
)

files=(
    /etc/bluetooth
    /usr/local/bin
    /etc/xbps.d/
    /etc/rc.conf
    /etc/rc.local
    /etc/svd
    /root/.fbtermrc
    /etc/sysctl.conf
    /etc/rsyslog.conf
    /etc/modprobe.d
    /etc/modules-load.d
    /etc/pam.d/sudo
    /etc/pam.d/slim
    /etc/pam.d/login
    /etc/pam.d/i3lock
    /etc/X11/xorg.conf
    /etc/dnscrypt-proxy.toml
    /etc/forwarding-rules.txt
    /etc/tor
    /etc/resolv.conf
    /etc/resolvconf.conf
    /etc/openvpn
    /etc/NetworkManager
    /etc/slim.conf
    /usr/share/slim/themes
    /usr/share/kbd/keymaps/i386/qwerty/us-nocaps.map.gz
    /etc/cgconfig.conf
    /etc/zzz.d/
    /etc/udev/rules.d/80-net-name-slot.rules
    /etc/iproute2/rt_tables
    /etc/audit/rules.d
    /etc/ntpd.conf
    /etc/rsyslog.conf
    /etc/default/
    /etc/runit/runsvdir/default/
    /etc/lxd-config.yaml
)

sudo rsync -v -RrlDpgo --delete --delete-excluded \
    "${blacklist[@]}" "${files[@]}" files/public

sudo rsync -v -RrlDpgo --delete "${private[@]}" files/private

sudo cat /etc/sudoers > files/private/etc/sudoers

sudo chown -v -R "$USER:$USER" files
