config: {}
networks:
- config:
    ipv4.address: 10.100.100.1/24
    ipv4.nat: "true"
    ipv6.address: fd42:720e:63bd:4d94::1/64
    ipv6.nat: "true"
  description: ""
  name: lxdbr0
  type: bridge
  project: default
storage_pools:
- config:
    source: /var/lib/lxd/storage-pools/default
    volatile.initial_source: /var/lib/lxd/storage-pools/default
  description: ""
  name: default
  driver: btrfs
profiles:
- config: {}
  description: Default LXD profile
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
- config:
    user.user-data: |
      #cloud-config
      runcmd:
        - 'sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf'
        - 'echo DISPLAY=:0 | tee -a /etc/environment'
        - 'echo PULSE_SERVER=unix:@{HOME}/.pulse-native | tee -a /etc/environment'
      packages:
        - x11-apps
        - mesa-utils
        - pulseaudio
  description: GUI LXD profile
  devices:
    PASocket1:
      bind: container
      connect: unix:/tmp/user/maiz/pulse/native
      gid: "1000"
      listen: unix:/home/maiz/.pulse-native
      mode: "0777"
      security.gid: "1000"
      security.uid: "1000"
      type: proxy
      uid: "1000"
    X0:
      bind: container
      connect: unix:@/tmp/.X11-unix/X0
      listen: unix:@/tmp/.X11-unix/X0
      security.gid: "1000"
      security.uid: "1000"
      type: proxy
  name: gui
- config:
    environment.DISPLAY: :0
    user.user-data: |
      #cloud-config
      runcmd:
        - 'sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf'
        - 'echo export PULSE_SERVER=unix:/tmp/.pulse-native | tee --append /home/ubuntu/.profile'
      packages:
        - x11-apps
        - mesa-utils
        - pulseaudio
  description: GUI LXD profile
  devices:
    PASocket:
      path: /tmp/.pulse-native
      source: /tmp/user/maiz/pulse/native
      type: disk
    X0:
      path: /tmp/.X11-unix/X0
      source: /tmp/.X11-unix/X0
      type: disk
    mygpu:
      type: gpu
  name: gui2
- config:
    user.user-data: |
      #cloud-config
      package_upgrade: true
      package_reboot_if_required: true
      packages:
        - pulseaudio
        - x11-apps
        - mesa-utils
        - ssh
        - sshpass
        - rsync
        - zsh
        - tmux
        - screen
        - neovim
        - fzf
        - bat
        - fd-find
        - jdupes
        - cargo
        - git
        - curl
        - gnupg
        - firefox-esr
        - ansible
        - apt-file
        - kali-linux-large
      manage_etc_hosts: "localhost"
      locale: en_US.UTF-8
      timezone: Europe/Paris
      users:
        - name: maiz
          ssh-authorized-keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/1pjUOiiCwG2HitnUhch8kkEPvcT7Wvwb8IClDXM4hgzC7Xn/kOuG2GAWuvuOH06e86QKDIELjuXNlaWcsM8fgsdCqq8+rdnyHQ794C3+SNUaFNHsUs/lxhUPuoWAWq08pBmz3WB28g1i9rnx+CM0+M9p8+bU9KMDPBnku5NNJ6wucKLcKi7CCWwKblDDE3PBFY0L3GUzF9qkoDgxgZsLpwKzKcnck+kQHPvBG4YvCcF9ROuMkwpNU9UOjUig9Lo25/OrZNTrt0lC2Z0IHm5nT2fOKYhJU8ASqORrjwp1Io1JmznZOrIGHkeUokGMSpvIEEX0UtbPOwwCBYJHgKN1vYHPdVERcQEijc5iYa9TarDixU6HNP2NcAY62d3Wr2ociH7E9LA0E4XBAzou0kVQp3HZ2GaS4jMLM2GTFyCgq4Sd4tX1X/G3oVvulEr0wbbDeKoSOnOOZT3JxcXlGnn7PdNbTfD/Fx7OFl+/2xUNuLhQ8St7rnNXdcKWEQKMpgDsH68y9cz7Av5ajWykK+TDqciEnYJcvPNQw+FfDTF0aMgxrDsds/N3uNWD73KZW4FgREhaBj9tYF8/mlWx7qsAQRCAlLsgrz4EDnoWMW7MVARITiIdsYTypMU//1ZMOVAV3QQxnv0TtFTfvM/OUpBSh0e8cw1SLXSM/yBsU0VF0w== (none)
          sudo: ['ALL=(ALL) NOPASSWD: ALL']
          groups: sudo
          shell: /usr/bin/zsh
      runcmd:
        - 'systemctl enable --now ssh'
        - 'ln -svf /usr/bin/batcat /usr/bin/bat'
        - 'cargo install lsd'
        - 'cp /root/.cargo/bin/lsd /usr/local/bin'
        - 'rm -rf /root/.cargo'
        - 'curl "https://raw.githubusercontent.com/zenfailure/pubfiles/master/install.bash" | bash'
        - 'su -l maiz -s /usr/bin/bash -c "curl \"https://raw.githubusercontent.com/zenfailure/pubfiles/master/install.bash\" | bash"'
  description: Kali LXD profile
  devices: {}
  name: kali
projects:
- config:
    features.images: "true"
    features.networks: "true"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
  description: Default LXD project
  name: default

